# Generated by Django 4.1.4 on 2022-12-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название фильма')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('actors', models.TextField(verbose_name='Актеры')),
                ('show_date', models.DateField(verbose_name='Дата показа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.category', verbose_name='Категория')),
            ],
        ),
    ]
